# Generated by Django 5.2.4 on 2025-08-05 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_project_github_url_remove_project_live_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='githubUrl',
            new_name='github_url',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='liveUrl',
            new_name='live_url',
        ),
    ]
